name: Docker Build and Push

env:
  IMAGE_NAME: ghrc.io/thakurnishu/portfolio
on:
  push:
    branches: [ "main" ]
    paths:
      - 'data.yaml'
      - '.github/workflows/docker-build-and-push.yaml'
  workflow_dispatch:
    inputs:
      action:
        description: 'Build'
        required: true
        type: choice
        options:
          - 'build'
        default: 'build' 

jobs:
  build-and-push:
    permissions:
      packages: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main' # Ensure we're checking out the correct branch
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image Commit ID
        env:
          REGISTRY: ghcr.io
          OWNER: ${{ github.actor }}
          IMAGE_NAME: ${{ github.repository }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .
          target: final
          push: true
          tags: |
            $REGISTRY/$OWNER/$IMAGE_NAME:$(git rev-parse HEAD)
      - name: Build and Push Docker Image Latest
        env:
          REGISTRY: ghcr.io
          OWNER: ${{ github.actor }}
          IMAGE_NAME: ${{ github.repository }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .
          target: final
          push: true
          tags: |
            $REGISTRY/$OWNER/$IMAGE_NAME:latest
