name: Docker Build and Push

env:
  IMAGE_NAME: ghrc.io/thakurnishu/portfolio
on:
  push:
    branches: [ "main" ]
    paths:
      - 'data.yaml'
      - '.github/workflows/docker-build-and-push.yaml'
  workflow_dispatch:
    inputs:
      action:
        description: 'Build'
        required: true
        type: choice
        options:
          - 'build'
        default: 'build' 

jobs:
  build-and-push:
    permissions:
      packages: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main' # Ensure we're checking out the correct branch
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        run: docker build -t ${{ env.IMAGE_NAME }} .
      - name: Push Image
        run: |
          commit_id=$(git rev-parse HEAD)
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:${commit_id}
          docker push ${{env.IMAGE_NAME }}:${commit_id}
          docker push ${{env.IMAGE_NAME }}:latest
